# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    services:
      zookeeper:
        image: zookeeper:3.9
        ports:
        - 2181:2181

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox
      run: |
        pip install tox

    - name: Toxit
      run: |
        tox -v

    - name: coverage xml
      run: |
        python -m coverage xml
      if: ${{ matrix.python-version == 3.10 }}

    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
      if: ${{ matrix.python-version == 3.10 }}
